// types.js
const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

const REAUTHENTICATE = 'REAUTHENTICATE';
const CLEAR_USER = 'CLEAR_USER';

const USER_CLEAR_ERROR = 'USER_CLEAR_ERROR';

export default {
    USER_LOGIN_REQUEST,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILURE,
    USER_LOGOUT_REQUEST,
    USER_LOGOUT_SUCCESS,
    USER_LOGOUT_FAILURE,
    REAUTHENTICATE,
    CLEAR_USER,
    USER_CLEAR_ERROR
}