// types.js
const FETCH_WORKSPACE_NODES_REQUEST = 'FETCH_WORKSPACE_NODES_REQUEST';
const FETCH_WORKSPACE_NODES_SUCCESS = 'FETCH_WORKSPACE_NODES_SUCCESS';
const FETCH_WORKSPACE_NODES_FAILURE = 'FETCH_WORKSPACE_NODES_FAILURE';

const ADD_WORKSPACE_NODE__REQUEST = 'ADD_WORKSPACE_NODE__REQUEST';
const ADD_WORKSPACE_NODE__SUCCESS = 'ADD_WORKSPACE_NODE__SUCCESS';
const ADD_WORKSPACE_NODE__FAILURE = 'ADD_WORKSPACE_NODE__FAILURE';

const INVALIDATE_WORKSPACE = 'INVALIDATE_WORKSPACE';


const RENAME_WORKSPACE_NODE__REQUEST = 'RENAME_WORKSPACE_NODE__REQUEST';
const RENAME_WORKSPACE_NODE__SUCCESS = 'RENAME_WORKSPACE_NODE__SUCCESS';
const RENAME_WORKSPACE_NODE__FAILURE = 'RENAME_WORKSPACE_NODE__FAILURE';

const DELETE_WORKSPACE_NODE__REQUEST = 'DELETE_WORKSPACE_NODE__REQUEST';
const DELETE_WORKSPACE_NODE__SUCCESS = 'DELETE_WORKSPACE_NODE__SUCCESS';
const DELETE_WORKSPACE_NODE__FAILURE = 'DELETE_WORKSPACE_NODE__FAILURE';


const MOVE_WORKSPACE_NODE__REQUEST = 'MOVE_WORKSPACE_NODE__REQUEST';
const MOVE_WORKSPACE_NODE__SUCCESS = 'MOVE_WORKSPACE_NODE__SUCCESS';
const MOVE_WORKSPACE_NODE__FAILURE = 'MOVE_WORKSPACE_NODE__FAILURE';

export default {
    FETCH_WORKSPACE_NODES_REQUEST,
    FETCH_WORKSPACE_NODES_SUCCESS,
    FETCH_WORKSPACE_NODES_FAILURE,
    ADD_WORKSPACE_NODE__REQUEST,
    ADD_WORKSPACE_NODE__SUCCESS,
    ADD_WORKSPACE_NODE__FAILURE,
    INVALIDATE_WORKSPACE,
    RENAME_WORKSPACE_NODE__REQUEST,
    RENAME_WORKSPACE_NODE__SUCCESS,
    RENAME_WORKSPACE_NODE__FAILURE,
    DELETE_WORKSPACE_NODE__REQUEST,
    DELETE_WORKSPACE_NODE__SUCCESS,
    DELETE_WORKSPACE_NODE__FAILURE,
    MOVE_WORKSPACE_NODE__REQUEST,
    MOVE_WORKSPACE_NODE__SUCCESS,
    MOVE_WORKSPACE_NODE__FAILURE
}