// types.js
const USER_REGISTER__REQUEST = 'USER_REGISTER__REQUEST';
const USER_REGISTER__SUCCESS = 'USER_REGISTER__SUCCESS';
const USER_REGISTER__FAILURE = 'USER_REGISTER__FAILURE';

const USER_REGISTER_ERROR__CLEAR = 'USER_REGISTER_ERROR__CLEAR';

export default {
    USER_REGISTER__REQUEST,
    USER_REGISTER__SUCCESS,
    USER_REGISTER__FAILURE,
    USER_REGISTER_ERROR__CLEAR
}