// types.js
import { 
    WEBSOCKET_ACCESS__REQUEST, 
    WEBSOCKET_ACCESS__SUCCESS, 
    WEBSOCKET_ACCESS__FAILURE, 
    WEBSOCKET_AUTH__SUCCESS, 
    WEBSOCKET_AUTH__FAILURE, 
    WEBSOCKET__CONNECTED, 
    WEBSOCKET__DISCONNECT, 
    WEBSOCKET_MESSAGE__SEND,
    WEBSOCKET__CLOSED,
    SHAREDB_DOC_AUTH__FAILURE,
    SHAREDB_DOC_SUB__REQUEST,
    SHAREDB_DOC_SUB__SUCCESS,
    SHAREDB_DOC_SUB__FAILURE,
    SHAREDB_DOC_UNSUB,
    SHAREDB_DOC_SUBMIT_OP,
    SHAREDB_DOC_RECEIVE_OP
} from '../../../middleware/websocketShared/types'


export default {
    WEBSOCKET_ACCESS__REQUEST,
    WEBSOCKET_ACCESS__SUCCESS,
    WEBSOCKET_ACCESS__FAILURE,
    WEBSOCKET_AUTH__SUCCESS,
    WEBSOCKET_AUTH__FAILURE,
    WEBSOCKET__CONNECTED,
    WEBSOCKET__DISCONNECT,
    WEBSOCKET_MESSAGE__SEND,
    WEBSOCKET__CLOSED,
    SHAREDB_DOC_AUTH__FAILURE,
    SHAREDB_DOC_SUB__REQUEST,
    SHAREDB_DOC_SUB__SUCCESS,
    SHAREDB_DOC_SUB__FAILURE,
    SHAREDB_DOC_UNSUB,
    SHAREDB_DOC_SUBMIT_OP,
    SHAREDB_DOC_RECEIVE_OP,
}