// types.js
// const FETCH_WORKSPACES_REQUEST = 'FETCH_WORKSPACES_REQUEST';
// const FETCH_WORKSPACES_SUCCESS = 'FETCH_WORKSPACES_SUCCESS';
// const FETCH_WORKSPACES_FAILURE = 'FETCH_WORKSPACES_FAILURE';

const ADD_WORKSPACE_SUCCESS = 'ADD_WORKSPACE_SUCCESS';
const INVALIDATE_WORKSPACES = 'INVALIDATE_WORKSPACES';

//----

const UI_WORKSPACES_TABLE_ITEM_NEW__START = 'UI_WORKSPACES_TABLE_ITEM_NEW__START';
const UI_WORKSPACES_TABLE_ITEM_NEW__STOP = 'UI_WORKSPACES_TABLE_ITEM_NEW__STOP';
const UI_WORKSPACES_TABLE_ITEM_NEW__SUBMITTING = 'UI_WORKSPACES_TABLE_ITEM_EDIT__SUBMITTING';
const UI_WORKSPACES_TABLE_ITEM_EDIT__START = 'UI_WORKSPACES_TABLE_ITEM_EDIT__START';
const UI_WORKSPACES_TABLE_ITEM_EDIT__STOP = 'UI_WORKSPACES_TABLE_ITEM_EDIT__STOP';
const UI_WORKSPACES_TABLE_ITEM_EDIT__SUBMITTING = 'UI_WORKSPACES_TABLE_ITEM_EDIT__SUBMITTING';
const UI_WORKSPACES_TABLE_ITEM_DELETING__SUBMITTING = 'UI_WORKSPACES_TABLE_ITEM_DELETING__SUBMITTING';
const UI_WORKSPACES_TABLE_ITEM_DELETING__STOP = 'UI_WORKSPACES_TABLE_ITEM_DELETING__STOP';

export default {
    // FETCH_WORKSPACES_REQUEST,
    // FETCH_WORKSPACES_SUCCESS,
    // FETCH_WORKSPACES_FAILURE,
    ADD_WORKSPACE_SUCCESS,
    INVALIDATE_WORKSPACES,

    UI_WORKSPACES_TABLE_ITEM_NEW__START,
    UI_WORKSPACES_TABLE_ITEM_NEW__STOP,
    UI_WORKSPACES_TABLE_ITEM_NEW__SUBMITTING,
    UI_WORKSPACES_TABLE_ITEM_EDIT__START,
    UI_WORKSPACES_TABLE_ITEM_EDIT__STOP,
    UI_WORKSPACES_TABLE_ITEM_EDIT__SUBMITTING,
    UI_WORKSPACES_TABLE_ITEM_DELETING__SUBMITTING,
    UI_WORKSPACES_TABLE_ITEM_DELETING__STOP
}