// types.js
const UI_OPEN_MODAL = 'UI_OPEN_MODAL';
const UI_CLOSE_MODAL = 'UI_CLOSE_MODAL';

const UI_DRAGGING_ELEM__START = 'UI_DRAGGING__START';
const UI_DRAGGING_ELEM__MOVE = 'UI_DRAGGING__MOVE';
const UI_DRAGGING_ELEM__STOP = 'UI_DRAGGING__STOP';

const UI_NODE_NEW_NAMING__START = 'UI_NODE_NEW_NAMING__START';
const UI_NODE_NEW_NAMING__STOP = 'UI_NODE_NEW_NAMING__STOP';

const UI_DROP_DOWN_MENU__OPEN = 'UI_DROP_DOWN_MENU__OPEN';
const UI_DROP_DOWN_MENU__CLOSE = 'UI_DROP_DOWN_MENU__CLOSE';

const UI_NAV_ACCOUNT_MENU__OPEN = 'UI_NAV_ACCOUNT_MENU__OPEN';
const UI_NAV_ACCOUNT_MENU__CLOSE = 'UI_NAV_ACCOUNT_MENU__CLOSE';
export default {
    UI_OPEN_MODAL,
    UI_CLOSE_MODAL,
    UI_NODE_NEW_NAMING__START,
    UI_NODE_NEW_NAMING__STOP,
    UI_DROP_DOWN_MENU__OPEN,
    UI_DROP_DOWN_MENU__CLOSE,
    UI_NAV_ACCOUNT_MENU__OPEN,
    UI_NAV_ACCOUNT_MENU__CLOSE,
    UI_DRAGGING_ELEM__START,
    UI_DRAGGING_ELEM__MOVE,
    UI_DRAGGING_ELEM__STOP
}